### ISSUE TITLE
(feat) name it

### ISSUE THREAD

**Issue by Nate-Wilkins** [runphilrun/ThrusterDesign#10]
All cool CLI tools have good names.

Potential Canidates
- `thrustr`: Thruster
- `thrst`: Thrust
- `rtd`: Rocket Thruster Design
- `rthrst`: Rocket Thrust

I prefer `rthrst` but this isn't my baby.

**Comment by runphilrun** [comment]
`thrstr` ? maybe we could try a "backronym" where we spell a word with an acronym. 

I want this to be easy to write from the command line too. hmm

`tdu` thruster design utility, pronounced "to-do" or "tee dee you"
`tdt` thruster design tool
`std` simple thruster design, as in `std get()`.....
`sedu` satellite engine design utility, reminiscient of `sudo`
`spdu` satellite propulsion design utility, pronounced "spidoo"
`tdesu` thruster design utility, pronounced "tee desoo"

Minor distinction but this is important to me: "rocket" implies a few things
1. That the system combusts fuel for propulsion (this thruster won't, it only accelerates pressurized gas)
2. That the vehicle operates in atmosphere and space, like a launch vehicle (it doesn't, it only operates in space)

**Additional key words that may be useful:**
`propulsion` `prop`
`design` `designer`
`cubesat` `small sat` `satellite` 
`simulation` `calculator`
`utility` `tool`
`python`
`simple`
`easy`
`cold-gas` `monopropellant`
`spacecraft`
`engine`
`system`

**Comment by Nate-Wilkins** [comment]
’simple-easy-tool’ perfect. :thumbsup:

**Comment by Nate-Wilkins** [comment]
I like ’tdu’ a lot.

**Comment by runphilrun** [comment]
Me too. In my head I've been reading it as "tee doo."

**Comment by Nate-Wilkins** [comment]
:dancer: Awesome! I'm going to go through and rename all of the refs to `tdu` (tee doo) then.

**Comment by Nate-Wilkins** [comment]
@runphilrun do you want to rename the repository to `tdu` or to `ThrusterDesignUtility`?
I like `tdu` mostly cause it's easy to remember and it's unique.

**Comment by runphilrun** [comment]
If we were to change it, it'd prefer `tdu`. Is renaming a repo as non-trivial as I think it is?
I will check over this pull request before committing it. Thanks for changing everything over!!

**Comment by Nate-Wilkins** [comment]
Yeah it's not trivial at all -> settings for this repo -> rename

**Comment by runphilrun** [comment]
but that will screw up all my links ):

**Comment by Nate-Wilkins** [comment]
:D even better!

**Comment by Nate-Wilkins** [comment]
@runphilrun before finishing off #14 could we rename the repository? I'd like to do that before putting anything up on pypi

**Comment by runphilrun** [comment]
Will rename when i get home from work

**Comment by runphilrun** [comment]
renamed repo to TDU
