### ISSUE TITLE
Installation issues/fixes

### ISSUE THREAD

**Issue by Beaudidly** [runphilrun/ThrusterDesign#14]
From the README.md in the root directory: `$ pip install tdu` results in: 
`Collecting tdu`

  `Could not find a version that satisfies the requirement tdu (from versions: )
No matching distribution found for tdu`

Also listing required pip packages in the README would be good, such as `sphinx` and `sphinx_rtd_theme`

**Comment by runphilrun** [comment]
Assigning issue to @Nate-Wilkins

**Comment by Nate-Wilkins** [comment]
@Beaudidly usually python packages have a `requirements.txt` file that contains these things, would it be nice to reference this file in the `README.md`?

@runphilrun I'll have to register `tdu` to pypi is that okay? (this is probably where we want to be eventually anyways)

**Comment by runphilrun** [comment]
>  I'll have to register tdu to pypi is that okay? (this is probably where we want to be eventually anyways)

yes, proceed with adding `tdu` to PyPI
