### ISSUE TITLE
Pressure Ratio Calculation

### ISSUE THREAD

**Issue by jprks** [runphilrun/ThrusterDesign#28]
I have gone over the math to get from (Pc/Pt)^(k-1/k) = Tc/Te to the pressure ratio and noticed that your equation is slightly incorrect. I found that the pressure ratio (Pc/Pe) = (Tc/Te)^(k/k-1) not = (Tc/Te)^(k-1/k).

**Comment by runphilrun** [comment]
corrected in [c3e3f8b](https://github.com/runphilrun/TDU/commit/c3e3f8b8d2de0d2cc1f45b0a1bcae3f4c98cf461)

```
(Pc/Pe)^((k-1)/k) = Tc/Te
((Pc/Pe)^((k-1)/k))^(k/(k-1)) = (Tc/Te)^(k/(k-1))
Pc/Pe = (Tc/Te)^(k/(k-1))
```

good catch
