### ISSUE TITLE
GitHub Wiki does not display math markdown

### ISSUE THREAD

**Issue by runphilrun** [runphilrun/ThrusterDesign#5]
There are a bunch of equations that do not display properly on the [Theory](https://github.com/runphilrun/ThrusterDesign/wiki/Theory) portion of the Wiki.

STEMN is able to parse LaTeX code as math equations. GitHub does not support LaTeX.

One possible alternative is [1TeX2img](http://www.sciweavers.org/free-online-latex-equation-editor), which converts LaTeX to an image that may be embedded on the page.

1) [bug] Equations need to be displayed properly (using images or otherwise).
2) [help wanted] All existing equations must be fixed.

**Comment by Nate-Wilkins** [comment]
Looks like latex isn't going to be supported anytime soon https://github.com/github/markup/issues/274

**Comment by Nate-Wilkins** [comment]
This is closely related to #6 - I've just found out that [Sphinx imgmath](http://www.sphinx-doc.org/en/stable/ext/math.html) has LaTeX support. :+1:

**Comment by runphilrun** [comment]
Correct. This issue is encapsulated by issue #6. Closing this issue.
